### ISSUE TITLE
big bugg

### ISSUE THREAD

**Issue by successed** [CryLegend/AuthMeBridge#15]
[06:11:43 WARN]: [AuthMeBridge] Task #44 for AuthMeBridge v1.6.2 generated an exception
java.lang.NoClassDefFoundError: fr/xephi/authme/api/NewAPI
        at com.crylegend.authmebridge.AuthMeBridgeListener$1.run(AuthMeBridgeListener.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-5f38d38-12698ea]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: fr.xephi.authme.api.NewAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-5f38d38-12698ea]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 8 more

**Comment by sgdc3** [comment]
Please stop using AuthMeBridge, use AuthMeBungee instead! (also update to the latest build of authme!)
https://ci.codemc.org/job/AuthMe/job/AuthMeBungee/
https://ci.codemc.org/job/AuthMe/job/AuthMeReloaded/

**Comment by successed** [comment]
> AuthMeBungee

is not work...

**Comment by sgdc3** [comment]
It works, you have to use both latest dev build of AuthMeBungee and AuthMeReloaded!!!
Also make sure that in the authme config file "Hooks.bungeecord" is set to true.

**Comment by successed** [comment]
> It works, you have to use both latest dev build of AuthMeBungee and AuthMeReloaded!!!
> Also make sure that in the authme config file "Hooks.bungeecord" is set to true.

already so and is not work.

**Comment by sgdc3** [comment]
Please post your AuthMeBungee and AuthMeReloaded configs (remove the passwords)

**Comment by successed** [comment]
bungeeauthme : https://hastebin.com/wusekuwesa.bash
authmeconfg : https://hastebin.com/amapigejor.bash

**Comment by sgdc3** [comment]
What does not work? AutoLogin?

**Comment by successed** [comment]
login is done but no message and command are written

**Comment by sgdc3** [comment]
can you record a video of the issue?
